<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>yunqi-courier-starter</artifactId>
    <parent>
        <groupId>yunqi.courier</groupId>
        <artifactId>yunqi-courier</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <dependencies>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-kernel</artifactId>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-registry-memory</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-registry-file</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-registry-zookeeper</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-serialization-json</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-serialization-cbor</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-proxying-jdk</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-proxying-bytebuddy</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-traffic-loadbalancing-random</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-traffic-loadbalancing-round-robin</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-traffic-loadbalancing-weighted</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-traffic-loadbalancing-least-active</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-compression-lz4</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-encryption-aes-gcm</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-encoding-utf8</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-binary2text-base64</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-binary2text-base64url</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-network-netty</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>yunqi.courier</groupId>
            <artifactId>yunqi-courier-telemetry-otlp</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
